package biz.fz5.app.kumquat.model.impl;

import biz.fz5.app.kumquat.model.ContactInfo;
import biz.fz5.app.kumquat.service.ContactInfoLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ContactInfo service. Represents a row in the &quot;Kumquat_ContactInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactInfoImpl
 * @see biz.fz5.app.kumquat.model.ContactInfo
 * @generated
 */
public abstract class ContactInfoBaseImpl extends ContactInfoModelImpl
    implements ContactInfo {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a contact info model instance should use the {@link ContactInfo} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ContactInfoLocalServiceUtil.addContactInfo(this);
        } else {
            ContactInfoLocalServiceUtil.updateContactInfo(this);
        }
    }
}
