package biz.fz5.app.kumquat.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ContactGroup service. Represents a row in the &quot;Kumquat_ContactGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link biz.fz5.app.kumquat.model.impl.ContactGroupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link biz.fz5.app.kumquat.model.impl.ContactGroupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactGroup
 * @see biz.fz5.app.kumquat.model.impl.ContactGroupImpl
 * @see biz.fz5.app.kumquat.model.impl.ContactGroupModelImpl
 * @generated
 */
public interface ContactGroupModel extends BaseModel<ContactGroup> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a contact group model instance should use the {@link ContactGroup} interface instead.
     */

    /**
     * Returns the primary key of this contact group.
     *
     * @return the primary key of this contact group
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this contact group.
     *
     * @param primaryKey the primary key of this contact group
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the contact group ID of this contact group.
     *
     * @return the contact group ID of this contact group
     */
    public long getContactGroupId();

    /**
     * Sets the contact group ID of this contact group.
     *
     * @param contactGroupId the contact group ID of this contact group
     */
    public void setContactGroupId(long contactGroupId);

    /**
     * Returns the company ID of this contact group.
     *
     * @return the company ID of this contact group
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this contact group.
     *
     * @param companyId the company ID of this contact group
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this contact group.
     *
     * @return the group ID of this contact group
     */
    public long getGroupId();

    /**
     * Sets the group ID of this contact group.
     *
     * @param groupId the group ID of this contact group
     */
    public void setGroupId(long groupId);

    /**
     * Returns the name of this contact group.
     *
     * @return the name of this contact group
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this contact group.
     *
     * @param name the name of this contact group
     */
    public void setName(String name);

    /**
     * Returns the description of this contact group.
     *
     * @return the description of this contact group
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this contact group.
     *
     * @param description the description of this contact group
     */
    public void setDescription(String description);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ContactGroup contactGroup);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ContactGroup> toCacheModel();

    @Override
    public ContactGroup toEscapedModel();

    @Override
    public ContactGroup toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
